import { JumpConditions, u8 } from '.';
import { ArithmeticTarget, Instruction } from './instruction';

export const unprefixed: Record<number, Instruction> = {
    0x00: new Instruction('NOP', 0),
    0x01: new Instruction('LD', ArithmeticTarget.BC, ArithmeticTarget.U16),
    0x02: new Instruction('LD', ArithmeticTarget.BCP, ArithmeticTarget.A),
    0x03: new Instruction('INC', ArithmeticTarget.BC),
    0x04: new Instruction('INC', ArithmeticTarget.B),
    0x05: new Instruction('DEC', ArithmeticTarget.B),
    0x06: new Instruction('LD', ArithmeticTarget.B, ArithmeticTarget.U8),
    0x07: new Instruction('RLCA', 0),
    0x08: new Instruction('LD', ArithmeticTarget.U16, ArithmeticTarget.SP),
    0x09: new Instruction('ADD', ArithmeticTarget.HL, ArithmeticTarget.BC),
    0x0a: new Instruction('LD', ArithmeticTarget.A, ArithmeticTarget.BCP),
    0x0b: new Instruction('DEC', ArithmeticTarget.BC),
    0x0c: new Instruction('INC', ArithmeticTarget.C),
    0x0d: new Instruction('DEC', ArithmeticTarget.C),
    0x0e: new Instruction('LD', ArithmeticTarget.C, ArithmeticTarget.U8),
    0x0f: new Instruction('RRCA', 0),

    0x10: new Instruction('STOP', 0), // 2-byte opcode (0x10 0x00); on CGB, doubles as the speed-switch trigger
    0x11: new Instruction('LD', ArithmeticTarget.DE, ArithmeticTarget.U16),
    0x12: new Instruction('LD', ArithmeticTarget.DEP, ArithmeticTarget.A),
    0x13: new Instruction('INC', ArithmeticTarget.DE),
    0x14: new Instruction('INC', ArithmeticTarget.D),
    0x15: new Instruction('DEC', ArithmeticTarget.D),
    0x16: new Instruction('LD', ArithmeticTarget.D, ArithmeticTarget.U8),
    0x17: new Instruction('RLA', 0),
    0x18: new Instruction('JR', JumpConditions.Always),
    0x19: new Instruction('ADD', ArithmeticTarget.HL, ArithmeticTarget.DE),
    0x1a: new Instruction('LD', ArithmeticTarget.A, ArithmeticTarget.DEP),
    0x1b: new Instruction('DEC', ArithmeticTarget.DE),
    0x1c: new Instruction('INC', ArithmeticTarget.E),
    0x1d: new Instruction('DEC', ArithmeticTarget.E),
    0x1e: new Instruction('LD', ArithmeticTarget.E, ArithmeticTarget.U8),
    0x1f: new Instruction('RRA', 0),

    0x20: new Instruction('JR', JumpConditions.NotZero),
    0x21: new Instruction('LD', ArithmeticTarget.HL, ArithmeticTarget.U16),
    0x22: new Instruction('LD', ArithmeticTarget.HLI, ArithmeticTarget.A),
    0x23: new Instruction('INC', ArithmeticTarget.HL),
    0x24: new Instruction('INC', ArithmeticTarget.H),
    0x25: new Instruction('DEC', ArithmeticTarget.H),
    0x26: new Instruction('LD', ArithmeticTarget.H, ArithmeticTarget.U8),
    0x27: new Instruction('DAA', 0),
    0x28: new Instruction('JR', JumpConditions.Zero),
    0x29: new Instruction('ADD', ArithmeticTarget.HL, ArithmeticTarget.HL),
    0x2a: new Instruction('LD', ArithmeticTarget.A, ArithmeticTarget.HLI),
    0x2b: new Instruction('DEC', ArithmeticTarget.HL),
    0x2c: new Instruction('INC', ArithmeticTarget.L),
    0x2d: new Instruction('DEC', ArithmeticTarget.L),
    0x2e: new Instruction('LD', ArithmeticTarget.L, ArithmeticTarget.U8),
    0x2f: new Instruction('CPL', 0),

    0x30: new Instruction('JR', JumpConditions.NotCarry),
    0x31: new Instruction('LD', ArithmeticTarget.SP, ArithmeticTarget.U16),
    0x32: new Instruction('LD', ArithmeticTarget.HLD, ArithmeticTarget.A),
    0x33: new Instruction('INC', ArithmeticTarget.SP),
    0x34: new Instruction('INC', ArithmeticTarget.HLP),
    0x35: new Instruction('DEC', ArithmeticTarget.HLP),
    0x36: new Instruction('LD', ArithmeticTarget.HLP, ArithmeticTarget.U8),
    0x37: new Instruction('SCF', 0),
    0x38: new Instruction('JR', JumpConditions.Carry),
    0x39: new Instruction('ADD', ArithmeticTarget.HL, ArithmeticTarget.SP),
    0x3a: new Instruction('LD', ArithmeticTarget.A, ArithmeticTarget.HLD),
    0x3b: new Instruction('DEC', ArithmeticTarget.SP),
    0x3c: new Instruction('INC', ArithmeticTarget.A),
    0x3d: new Instruction('DEC', ArithmeticTarget.A),
    0x3e: new Instruction('LD', ArithmeticTarget.A, ArithmeticTarget.U8),
    0x3f: new Instruction('CCF', 0),

    0x40: new Instruction('LD', ArithmeticTarget.B, ArithmeticTarget.B),
    0x41: new Instruction('LD', ArithmeticTarget.B, ArithmeticTarget.C),
    0x42: new Instruction('LD', ArithmeticTarget.B, ArithmeticTarget.D),
    0x43: new Instruction('LD', ArithmeticTarget.B, ArithmeticTarget.E),
    0x44: new Instruction('LD', ArithmeticTarget.B, ArithmeticTarget.H),
    0x45: new Instruction('LD', ArithmeticTarget.B, ArithmeticTarget.L),
    0x46: new Instruction('LD', ArithmeticTarget.B, ArithmeticTarget.HLP),
    0x47: new Instruction('LD', ArithmeticTarget.B, ArithmeticTarget.A),
    0x48: new Instruction('LD', ArithmeticTarget.C, ArithmeticTarget.B),
    0x49: new Instruction('LD', ArithmeticTarget.C, ArithmeticTarget.C),
    0x4a: new Instruction('LD', ArithmeticTarget.C, ArithmeticTarget.D),
    0x4b: new Instruction('LD', ArithmeticTarget.C, ArithmeticTarget.E),
    0x4c: new Instruction('LD', ArithmeticTarget.C, ArithmeticTarget.H),
    0x4d: new Instruction('LD', ArithmeticTarget.C, ArithmeticTarget.L),
    0x4e: new Instruction('LD', ArithmeticTarget.C, ArithmeticTarget.HLP),
    0x4f: new Instruction('LD', ArithmeticTarget.C, ArithmeticTarget.A),

    0x50: new Instruction('LD', ArithmeticTarget.D, ArithmeticTarget.B),
    0x51: new Instruction('LD', ArithmeticTarget.D, ArithmeticTarget.C),
    0x52: new Instruction('LD', ArithmeticTarget.D, ArithmeticTarget.D),
    0x53: new Instruction('LD', ArithmeticTarget.D, ArithmeticTarget.E),
    0x54: new Instruction('LD', ArithmeticTarget.D, ArithmeticTarget.H),
    0x55: new Instruction('LD', ArithmeticTarget.D, ArithmeticTarget.L),
    0x56: new Instruction('LD', ArithmeticTarget.D, ArithmeticTarget.HLP),
    0x57: new Instruction('LD', ArithmeticTarget.D, ArithmeticTarget.A),
    0x58: new Instruction('LD', ArithmeticTarget.E, ArithmeticTarget.B),
    0x59: new Instruction('LD', ArithmeticTarget.E, ArithmeticTarget.C),
    0x5a: new Instruction('LD', ArithmeticTarget.E, ArithmeticTarget.D),
    0x5b: new Instruction('LD', ArithmeticTarget.E, ArithmeticTarget.E),
    0x5c: new Instruction('LD', ArithmeticTarget.E, ArithmeticTarget.H),
    0x5d: new Instruction('LD', ArithmeticTarget.E, ArithmeticTarget.L),
    0x5e: new Instruction('LD', ArithmeticTarget.E, ArithmeticTarget.HLP),
    0x5f: new Instruction('LD', ArithmeticTarget.E, ArithmeticTarget.A),

    0x60: new Instruction('LD', ArithmeticTarget.H, ArithmeticTarget.B),
    0x61: new Instruction('LD', ArithmeticTarget.H, ArithmeticTarget.C),
    0x62: new Instruction('LD', ArithmeticTarget.H, ArithmeticTarget.D),
    0x63: new Instruction('LD', ArithmeticTarget.H, ArithmeticTarget.E),
    0x64: new Instruction('LD', ArithmeticTarget.H, ArithmeticTarget.H),
    0x65: new Instruction('LD', ArithmeticTarget.H, ArithmeticTarget.L),
    0x66: new Instruction('LD', ArithmeticTarget.H, ArithmeticTarget.HLP),
    0x67: new Instruction('LD', ArithmeticTarget.H, ArithmeticTarget.A),
    0x68: new Instruction('LD', ArithmeticTarget.L, ArithmeticTarget.B),
    0x69: new Instruction('LD', ArithmeticTarget.L, ArithmeticTarget.C),
    0x6a: new Instruction('LD', ArithmeticTarget.L, ArithmeticTarget.D),
    0x6b: new Instruction('LD', ArithmeticTarget.L, ArithmeticTarget.E),
    0x6c: new Instruction('LD', ArithmeticTarget.L, ArithmeticTarget.H),
    0x6d: new Instruction('LD', ArithmeticTarget.L, ArithmeticTarget.L),
    0x6e: new Instruction('LD', ArithmeticTarget.L, ArithmeticTarget.HLP),
    0x6f: new Instruction('LD', ArithmeticTarget.L, ArithmeticTarget.A),

    0x70: new Instruction('LD', ArithmeticTarget.HLP, ArithmeticTarget.B),
    0x71: new Instruction('LD', ArithmeticTarget.HLP, ArithmeticTarget.C),
    0x72: new Instruction('LD', ArithmeticTarget.HLP, ArithmeticTarget.D),
    0x73: new Instruction('LD', ArithmeticTarget.HLP, ArithmeticTarget.E),
    0x74: new Instruction('LD', ArithmeticTarget.HLP, ArithmeticTarget.H),
    0x75: new Instruction('LD', ArithmeticTarget.HLP, ArithmeticTarget.L),
    0x76: new Instruction('HALT', 0),
    0x77: new Instruction('LD', ArithmeticTarget.HLP, ArithmeticTarget.A),
    0x78: new Instruction('LD', ArithmeticTarget.A, ArithmeticTarget.B),
    0x79: new Instruction('LD', ArithmeticTarget.A, ArithmeticTarget.C),
    0x7a: new Instruction('LD', ArithmeticTarget.A, ArithmeticTarget.D),
    0x7b: new Instruction('LD', ArithmeticTarget.A, ArithmeticTarget.E),
    0x7c: new Instruction('LD', ArithmeticTarget.A, ArithmeticTarget.H),
    0x7d: new Instruction('LD', ArithmeticTarget.A, ArithmeticTarget.L),
    0x7e: new Instruction('LD', ArithmeticTarget.A, ArithmeticTarget.HLP),
    0x7f: new Instruction('LD', ArithmeticTarget.A, ArithmeticTarget.A),

    0x80: new Instruction('ADD', ArithmeticTarget.B),
    0x81: new Instruction('ADD', ArithmeticTarget.C),
    0x82: new Instruction('ADD', ArithmeticTarget.D),
    0x83: new Instruction('ADD', ArithmeticTarget.E),
    0x84: new Instruction('ADD', ArithmeticTarget.H),
    0x85: new Instruction('ADD', ArithmeticTarget.L),
    0x86: new Instruction('ADD', ArithmeticTarget.HLP),
    0x87: new Instruction('ADD', ArithmeticTarget.A),
    0x88: new Instruction('ADC', ArithmeticTarget.B),
    0x89: new Instruction('ADC', ArithmeticTarget.C),
    0x8a: new Instruction('ADC', ArithmeticTarget.D),
    0x8b: new Instruction('ADC', ArithmeticTarget.E),
    0x8c: new Instruction('ADC', ArithmeticTarget.H),
    0x8d: new Instruction('ADC', ArithmeticTarget.L),
    0x8e: new Instruction('ADC', ArithmeticTarget.HLP),
    0x8f: new Instruction('ADC', ArithmeticTarget.A),

    0x90: new Instruction('SUB', ArithmeticTarget.B),
    0x91: new Instruction('SUB', ArithmeticTarget.C),
    0x92: new Instruction('SUB', ArithmeticTarget.D),
    0x93: new Instruction('SUB', ArithmeticTarget.E),
    0x94: new Instruction('SUB', ArithmeticTarget.H),
    0x95: new Instruction('SUB', ArithmeticTarget.L),
    0x96: new Instruction('SUB', ArithmeticTarget.HLP),
    0x97: new Instruction('SUB', ArithmeticTarget.A),
    0x98: new Instruction('SBC', ArithmeticTarget.B),
    0x99: new Instruction('SBC', ArithmeticTarget.C),
    0x9a: new Instruction('SBC', ArithmeticTarget.D),
    0x9b: new Instruction('SBC', ArithmeticTarget.E),
    0x9c: new Instruction('SBC', ArithmeticTarget.H),
    0x9d: new Instruction('SBC', ArithmeticTarget.L),
    0x9e: new Instruction('SBC', ArithmeticTarget.HLP),
    0x9f: new Instruction('SBC', ArithmeticTarget.A),

    0xa0: new Instruction('AND', ArithmeticTarget.B),
    0xa1: new Instruction('AND', ArithmeticTarget.C),
    0xa2: new Instruction('AND', ArithmeticTarget.D),
    0xa3: new Instruction('AND', ArithmeticTarget.E),
    0xa4: new Instruction('AND', ArithmeticTarget.H),
    0xa5: new Instruction('AND', ArithmeticTarget.L),
    0xa6: new Instruction('AND', ArithmeticTarget.HLP),
    0xa7: new Instruction('AND', ArithmeticTarget.A),
    0xa8: new Instruction('XOR', ArithmeticTarget.B),
    0xa9: new Instruction('XOR', ArithmeticTarget.C),
    0xaa: new Instruction('XOR', ArithmeticTarget.D),
    0xab: new Instruction('XOR', ArithmeticTarget.E),
    0xac: new Instruction('XOR', ArithmeticTarget.H),
    0xad: new Instruction('XOR', ArithmeticTarget.L),
    0xae: new Instruction('XOR', ArithmeticTarget.HLP),
    0xaf: new Instruction('XOR', ArithmeticTarget.A),

    0xb0: new Instruction('OR', ArithmeticTarget.B),
    0xb1: new Instruction('OR', ArithmeticTarget.C),
    0xb2: new Instruction('OR', ArithmeticTarget.D),
    0xb3: new Instruction('OR', ArithmeticTarget.E),
    0xb4: new Instruction('OR', ArithmeticTarget.H),
    0xb5: new Instruction('OR', ArithmeticTarget.L),
    0xb6: new Instruction('OR', ArithmeticTarget.HLP),
    0xb7: new Instruction('OR', ArithmeticTarget.A),
    0xb8: new Instruction('CP', ArithmeticTarget.B),
    0xb9: new Instruction('CP', ArithmeticTarget.C),
    0xba: new Instruction('CP', ArithmeticTarget.D),
    0xbb: new Instruction('CP', ArithmeticTarget.E),
    0xbc: new Instruction('CP', ArithmeticTarget.H),
    0xbd: new Instruction('CP', ArithmeticTarget.L),
    0xbe: new Instruction('CP', ArithmeticTarget.HLP),
    0xbf: new Instruction('CP', ArithmeticTarget.A),

    0xc0: new Instruction('RET', JumpConditions.NotZero),
    0xc1: new Instruction('POP', ArithmeticTarget.BC),
    0xc2: new Instruction('JP', JumpConditions.NotZero),
    0xc3: new Instruction('JP', JumpConditions.Always),
    0xc4: new Instruction('CALL', JumpConditions.NotZero),
    0xc5: new Instruction('PUSH', ArithmeticTarget.BC),
    0xc6: new Instruction('ADD', ArithmeticTarget.U8),
    0xc7: new Instruction('RST', 0x0),
    0xc8: new Instruction('RET', JumpConditions.Zero),
    0xc9: new Instruction('RET', JumpConditions.Always),
    0xca: new Instruction('JP', JumpConditions.Zero),
    0xcb: new Instruction('NOP', 0), // should never be hit instead goes to prefixed opcodes object
    0xcc: new Instruction('CALL', JumpConditions.Zero),
    0xcd: new Instruction('CALL', JumpConditions.Always),
    0xce: new Instruction('ADC', ArithmeticTarget.U8),
    0xcf: new Instruction('RST', 0x08),

    0xd0: new Instruction('RET', JumpConditions.NotCarry),
    0xd1: new Instruction('POP', ArithmeticTarget.DE),
    0xd2: new Instruction('JP', JumpConditions.NotCarry),
    // 0xD3: no operation
    0xd4: new Instruction('CALL', JumpConditions.NotCarry),
    0xd5: new Instruction('PUSH', ArithmeticTarget.DE),
    0xd6: new Instruction('SUB', ArithmeticTarget.U8),
    0xd7: new Instruction('RST', 0x10),
    0xd8: new Instruction('RET', JumpConditions.Carry),
    0xd9: new Instruction('RETI', 0),
    0xda: new Instruction('JP', JumpConditions.Carry),
    // 0xDB: no operation
    0xdc: new Instruction('CALL', JumpConditions.Carry),
    // 0xDD: no operation
    0xde: new Instruction('SBC', ArithmeticTarget.U8),
    0xdf: new Instruction('RST', 0x18),

    0xe0: new Instruction('LD', ArithmeticTarget.FFU8P, ArithmeticTarget.A),
    0xe1: new Instruction('POP', ArithmeticTarget.HL),
    0xe2: new Instruction('LD', ArithmeticTarget.FFCP, ArithmeticTarget.A),
    // 0xE3: no operation
    // 0xE4: no operation
    0xe5: new Instruction('PUSH', ArithmeticTarget.HL),
    0xe6: new Instruction('AND', ArithmeticTarget.U8),
    0xe7: new Instruction('RST', 0x20),
    0xe8: new Instruction('ADD', ArithmeticTarget.SP),
    0xe9: new Instruction('JP', ArithmeticTarget.HL),
    0xea: new Instruction('LD', ArithmeticTarget.U16, ArithmeticTarget.A),
    // 0xEB: no operation
    // 0xEC: no operation
    // 0xED: no operation
    0xee: new Instruction('XOR', ArithmeticTarget.U8),
    0xef: new Instruction('RST', 0x28),

    0xf0: new Instruction('LD', ArithmeticTarget.A, ArithmeticTarget.FFU8P),
    0xf1: new Instruction('POP', ArithmeticTarget.AF),
    0xf2: new Instruction('LD', ArithmeticTarget.A, ArithmeticTarget.FFCP),
    0xf3: new Instruction('DI', 0),
    // 0xF4: no operation
    0xf5: new Instruction('PUSH', ArithmeticTarget.AF),
    0xf6: new Instruction('OR', ArithmeticTarget.U8),
    0xf7: new Instruction('RST', 0x30),
    0xf8: new Instruction('LD', ArithmeticTarget.HL, ArithmeticTarget.SPI8),
    0xf9: new Instruction('LD', ArithmeticTarget.SP, ArithmeticTarget.HL),
    0xfa: new Instruction('LD', ArithmeticTarget.A, ArithmeticTarget.U16P),
    0xfb: new Instruction('EI', 0),
    // 0xFC: no operation
    // 0xFD: no operation
    0xfe: new Instruction('CP', ArithmeticTarget.U8),
    0xff: new Instruction('RST', 0x38),
};

export const prefixed: Record<number, Instruction> = {
    0x00: new Instruction('RLC', ArithmeticTarget.B),
    0x01: new Instruction('RLC', ArithmeticTarget.C),
    0x02: new Instruction('RLC', ArithmeticTarget.D),
    0x03: new Instruction('RLC', ArithmeticTarget.E),
    0x04: new Instruction('RLC', ArithmeticTarget.H),
    0x05: new Instruction('RLC', ArithmeticTarget.L),
    0x06: new Instruction('RLC', ArithmeticTarget.HLP),
    0x07: new Instruction('RLC', ArithmeticTarget.A),
    0x08: new Instruction('RRC', ArithmeticTarget.B),
    0x09: new Instruction('RRC', ArithmeticTarget.C),
    0x0a: new Instruction('RRC', ArithmeticTarget.D),
    0x0b: new Instruction('RRC', ArithmeticTarget.E),
    0x0c: new Instruction('RRC', ArithmeticTarget.H),
    0x0d: new Instruction('RRC', ArithmeticTarget.L),
    0x0e: new Instruction('RRC', ArithmeticTarget.HLP),
    0x0f: new Instruction('RRC', ArithmeticTarget.A),

    0x10: new Instruction('RL', ArithmeticTarget.B),
    0x11: new Instruction('RL', ArithmeticTarget.C),
    0x12: new Instruction('RL', ArithmeticTarget.D),
    0x13: new Instruction('RL', ArithmeticTarget.E),
    0x14: new Instruction('RL', ArithmeticTarget.H),
    0x15: new Instruction('RL', ArithmeticTarget.L),
    0x16: new Instruction('RL', ArithmeticTarget.HLP),
    0x17: new Instruction('RL', ArithmeticTarget.A),
    0x18: new Instruction('RR', ArithmeticTarget.B),
    0x19: new Instruction('RR', ArithmeticTarget.C),
    0x1a: new Instruction('RR', ArithmeticTarget.D),
    0x1b: new Instruction('RR', ArithmeticTarget.E),
    0x1c: new Instruction('RR', ArithmeticTarget.H),
    0x1d: new Instruction('RR', ArithmeticTarget.L),
    0x1e: new Instruction('RR', ArithmeticTarget.HLP),
    0x1f: new Instruction('RR', ArithmeticTarget.A),

    0x20: new Instruction('SLA', ArithmeticTarget.B),
    0x21: new Instruction('SLA', ArithmeticTarget.C),
    0x22: new Instruction('SLA', ArithmeticTarget.D),
    0x23: new Instruction('SLA', ArithmeticTarget.E),
    0x24: new Instruction('SLA', ArithmeticTarget.H),
    0x25: new Instruction('SLA', ArithmeticTarget.L),
    0x26: new Instruction('SLA', ArithmeticTarget.HLP),
    0x27: new Instruction('SLA', ArithmeticTarget.A),
    0x28: new Instruction('SRA', ArithmeticTarget.B),
    0x29: new Instruction('SRA', ArithmeticTarget.C),
    0x2a: new Instruction('SRA', ArithmeticTarget.D),
    0x2b: new Instruction('SRA', ArithmeticTarget.E),
    0x2c: new Instruction('SRA', ArithmeticTarget.H),
    0x2d: new Instruction('SRA', ArithmeticTarget.L),
    0x2e: new Instruction('SRA', ArithmeticTarget.HLP),
    0x2f: new Instruction('SRA', ArithmeticTarget.A),

    0x30: new Instruction('SWAP', ArithmeticTarget.B),
    0x31: new Instruction('SWAP', ArithmeticTarget.C),
    0x32: new Instruction('SWAP', ArithmeticTarget.D),
    0x33: new Instruction('SWAP', ArithmeticTarget.E),
    0x34: new Instruction('SWAP', ArithmeticTarget.H),
    0x35: new Instruction('SWAP', ArithmeticTarget.L),
    0x36: new Instruction('SWAP', ArithmeticTarget.HLP),
    0x37: new Instruction('SWAP', ArithmeticTarget.A),
    0x38: new Instruction('SRL', ArithmeticTarget.B),
    0x39: new Instruction('SRL', ArithmeticTarget.C),
    0x3a: new Instruction('SRL', ArithmeticTarget.D),
    0x3b: new Instruction('SRL', ArithmeticTarget.E),
    0x3c: new Instruction('SRL', ArithmeticTarget.H),
    0x3d: new Instruction('SRL', ArithmeticTarget.L),
    0x3e: new Instruction('SRL', ArithmeticTarget.HLP),
    0x3f: new Instruction('SRL', ArithmeticTarget.A),

    0x40: new Instruction('BIT', 0, ArithmeticTarget.B),
    0x41: new Instruction('BIT', 0, ArithmeticTarget.C),
    0x42: new Instruction('BIT', 0, ArithmeticTarget.D),
    0x43: new Instruction('BIT', 0, ArithmeticTarget.E),
    0x44: new Instruction('BIT', 0, ArithmeticTarget.H),
    0x45: new Instruction('BIT', 0, ArithmeticTarget.L),
    0x46: new Instruction('BIT', 0, ArithmeticTarget.HLP),
    0x47: new Instruction('BIT', 0, ArithmeticTarget.A),
    0x48: new Instruction('BIT', 1, ArithmeticTarget.B),
    0x49: new Instruction('BIT', 1, ArithmeticTarget.C),
    0x4a: new Instruction('BIT', 1, ArithmeticTarget.D),
    0x4b: new Instruction('BIT', 1, ArithmeticTarget.E),
    0x4c: new Instruction('BIT', 1, ArithmeticTarget.H),
    0x4d: new Instruction('BIT', 1, ArithmeticTarget.L),
    0x4e: new Instruction('BIT', 1, ArithmeticTarget.HLP),
    0x4f: new Instruction('BIT', 1, ArithmeticTarget.A),

    0x50: new Instruction('BIT', 2, ArithmeticTarget.B),
    0x51: new Instruction('BIT', 2, ArithmeticTarget.C),
    0x52: new Instruction('BIT', 2, ArithmeticTarget.D),
    0x53: new Instruction('BIT', 2, ArithmeticTarget.E),
    0x54: new Instruction('BIT', 2, ArithmeticTarget.H),
    0x55: new Instruction('BIT', 2, ArithmeticTarget.L),
    0x56: new Instruction('BIT', 2, ArithmeticTarget.HLP),
    0x57: new Instruction('BIT', 2, ArithmeticTarget.A),
    0x58: new Instruction('BIT', 3, ArithmeticTarget.B),
    0x59: new Instruction('BIT', 3, ArithmeticTarget.C),
    0x5a: new Instruction('BIT', 3, ArithmeticTarget.D),
    0x5b: new Instruction('BIT', 3, ArithmeticTarget.E),
    0x5c: new Instruction('BIT', 3, ArithmeticTarget.H),
    0x5d: new Instruction('BIT', 3, ArithmeticTarget.L),
    0x5e: new Instruction('BIT', 3, ArithmeticTarget.HLP),
    0x5f: new Instruction('BIT', 3, ArithmeticTarget.A),

    0x60: new Instruction('BIT', 4, ArithmeticTarget.B),
    0x61: new Instruction('BIT', 4, ArithmeticTarget.C),
    0x62: new Instruction('BIT', 4, ArithmeticTarget.D),
    0x63: new Instruction('BIT', 4, ArithmeticTarget.E),
    0x64: new Instruction('BIT', 4, ArithmeticTarget.H),
    0x65: new Instruction('BIT', 4, ArithmeticTarget.L),
    0x66: new Instruction('BIT', 4, ArithmeticTarget.HLP),
    0x67: new Instruction('BIT', 4, ArithmeticTarget.A),
    0x68: new Instruction('BIT', 5, ArithmeticTarget.B),
    0x69: new Instruction('BIT', 5, ArithmeticTarget.C),
    0x6a: new Instruction('BIT', 5, ArithmeticTarget.D),
    0x6b: new Instruction('BIT', 5, ArithmeticTarget.E),
    0x6c: new Instruction('BIT', 5, ArithmeticTarget.H),
    0x6d: new Instruction('BIT', 5, ArithmeticTarget.L),
    0x6e: new Instruction('BIT', 5, ArithmeticTarget.HLP),
    0x6f: new Instruction('BIT', 5, ArithmeticTarget.A),

    0x70: new Instruction('BIT', 6, ArithmeticTarget.B),
    0x71: new Instruction('BIT', 6, ArithmeticTarget.C),
    0x72: new Instruction('BIT', 6, ArithmeticTarget.D),
    0x73: new Instruction('BIT', 6, ArithmeticTarget.E),
    0x74: new Instruction('BIT', 6, ArithmeticTarget.H),
    0x75: new Instruction('BIT', 6, ArithmeticTarget.L),
    0x76: new Instruction('BIT', 6, ArithmeticTarget.HLP),
    0x77: new Instruction('BIT', 6, ArithmeticTarget.A),
    0x78: new Instruction('BIT', 7, ArithmeticTarget.B),
    0x79: new Instruction('BIT', 7, ArithmeticTarget.C),
    0x7a: new Instruction('BIT', 7, ArithmeticTarget.D),
    0x7b: new Instruction('BIT', 7, ArithmeticTarget.E),
    0x7c: new Instruction('BIT', 7, ArithmeticTarget.H),
    0x7d: new Instruction('BIT', 7, ArithmeticTarget.L),
    0x7e: new Instruction('BIT', 7, ArithmeticTarget.HLP),
    0x7f: new Instruction('BIT', 7, ArithmeticTarget.A),

    0x80: new Instruction('RES', 0, ArithmeticTarget.B),
    0x81: new Instruction('RES', 0, ArithmeticTarget.C),
    0x82: new Instruction('RES', 0, ArithmeticTarget.D),
    0x83: new Instruction('RES', 0, ArithmeticTarget.E),
    0x84: new Instruction('RES', 0, ArithmeticTarget.H),
    0x85: new Instruction('RES', 0, ArithmeticTarget.L),
    0x86: new Instruction('RES', 0, ArithmeticTarget.HLP),
    0x87: new Instruction('RES', 0, ArithmeticTarget.A),
    0x88: new Instruction('RES', 1, ArithmeticTarget.B),
    0x89: new Instruction('RES', 1, ArithmeticTarget.C),
    0x8a: new Instruction('RES', 1, ArithmeticTarget.D),
    0x8b: new Instruction('RES', 1, ArithmeticTarget.E),
    0x8c: new Instruction('RES', 1, ArithmeticTarget.H),
    0x8d: new Instruction('RES', 1, ArithmeticTarget.L),
    0x8e: new Instruction('RES', 1, ArithmeticTarget.HLP),
    0x8f: new Instruction('RES', 1, ArithmeticTarget.A),

    0x90: new Instruction('RES', 2, ArithmeticTarget.B),
    0x91: new Instruction('RES', 2, ArithmeticTarget.C),
    0x92: new Instruction('RES', 2, ArithmeticTarget.D),
    0x93: new Instruction('RES', 2, ArithmeticTarget.E),
    0x94: new Instruction('RES', 2, ArithmeticTarget.H),
    0x95: new Instruction('RES', 2, ArithmeticTarget.L),
    0x96: new Instruction('RES', 2, ArithmeticTarget.HLP),
    0x97: new Instruction('RES', 2, ArithmeticTarget.A),
    0x98: new Instruction('RES', 3, ArithmeticTarget.B),
    0x99: new Instruction('RES', 3, ArithmeticTarget.C),
    0x9a: new Instruction('RES', 3, ArithmeticTarget.D),
    0x9b: new Instruction('RES', 3, ArithmeticTarget.E),
    0x9c: new Instruction('RES', 3, ArithmeticTarget.H),
    0x9d: new Instruction('RES', 3, ArithmeticTarget.L),
    0x9e: new Instruction('RES', 3, ArithmeticTarget.HLP),
    0x9f: new Instruction('RES', 3, ArithmeticTarget.A),

    0xa0: new Instruction('RES', 4, ArithmeticTarget.B),
    0xa1: new Instruction('RES', 4, ArithmeticTarget.C),
    0xa2: new Instruction('RES', 4, ArithmeticTarget.D),
    0xa3: new Instruction('RES', 4, ArithmeticTarget.E),
    0xa4: new Instruction('RES', 4, ArithmeticTarget.H),
    0xa5: new Instruction('RES', 4, ArithmeticTarget.L),
    0xa6: new Instruction('RES', 4, ArithmeticTarget.HLP),
    0xa7: new Instruction('RES', 4, ArithmeticTarget.A),
    0xa8: new Instruction('RES', 5, ArithmeticTarget.B),
    0xa9: new Instruction('RES', 5, ArithmeticTarget.C),
    0xaa: new Instruction('RES', 5, ArithmeticTarget.D),
    0xab: new Instruction('RES', 5, ArithmeticTarget.E),
    0xac: new Instruction('RES', 5, ArithmeticTarget.H),
    0xad: new Instruction('RES', 5, ArithmeticTarget.L),
    0xae: new Instruction('RES', 5, ArithmeticTarget.HLP),
    0xaf: new Instruction('RES', 5, ArithmeticTarget.A),

    0xb0: new Instruction('RES', 6, ArithmeticTarget.B),
    0xb1: new Instruction('RES', 6, ArithmeticTarget.C),
    0xb2: new Instruction('RES', 6, ArithmeticTarget.D),
    0xb3: new Instruction('RES', 6, ArithmeticTarget.E),
    0xb4: new Instruction('RES', 6, ArithmeticTarget.H),
    0xb5: new Instruction('RES', 6, ArithmeticTarget.L),
    0xb6: new Instruction('RES', 6, ArithmeticTarget.HLP),
    0xb7: new Instruction('RES', 6, ArithmeticTarget.A),
    0xb8: new Instruction('RES', 7, ArithmeticTarget.B),
    0xb9: new Instruction('RES', 7, ArithmeticTarget.C),
    0xba: new Instruction('RES', 7, ArithmeticTarget.D),
    0xbb: new Instruction('RES', 7, ArithmeticTarget.E),
    0xbc: new Instruction('RES', 7, ArithmeticTarget.H),
    0xbd: new Instruction('RES', 7, ArithmeticTarget.L),
    0xbe: new Instruction('RES', 7, ArithmeticTarget.HLP),
    0xbf: new Instruction('RES', 7, ArithmeticTarget.A),

    0xc0: new Instruction('SET', 0, ArithmeticTarget.B),
    0xc1: new Instruction('SET', 0, ArithmeticTarget.C),
    0xc2: new Instruction('SET', 0, ArithmeticTarget.D),
    0xc3: new Instruction('SET', 0, ArithmeticTarget.E),
    0xc4: new Instruction('SET', 0, ArithmeticTarget.H),
    0xc5: new Instruction('SET', 0, ArithmeticTarget.L),
    0xc6: new Instruction('SET', 0, ArithmeticTarget.HLP),
    0xc7: new Instruction('SET', 0, ArithmeticTarget.A),
    0xc8: new Instruction('SET', 1, ArithmeticTarget.B),
    0xc9: new Instruction('SET', 1, ArithmeticTarget.C),
    0xca: new Instruction('SET', 1, ArithmeticTarget.D),
    0xcb: new Instruction('SET', 1, ArithmeticTarget.E),
    0xcc: new Instruction('SET', 1, ArithmeticTarget.H),
    0xcd: new Instruction('SET', 1, ArithmeticTarget.L),
    0xce: new Instruction('SET', 1, ArithmeticTarget.HLP),
    0xcf: new Instruction('SET', 1, ArithmeticTarget.A),

    0xd0: new Instruction('SET', 2, ArithmeticTarget.B),
    0xd1: new Instruction('SET', 2, ArithmeticTarget.C),
    0xd2: new Instruction('SET', 2, ArithmeticTarget.D),
    0xd3: new Instruction('SET', 2, ArithmeticTarget.E),
    0xd4: new Instruction('SET', 2, ArithmeticTarget.H),
    0xd5: new Instruction('SET', 2, ArithmeticTarget.L),
    0xd6: new Instruction('SET', 2, ArithmeticTarget.HLP),
    0xd7: new Instruction('SET', 2, ArithmeticTarget.A),
    0xd8: new Instruction('SET', 3, ArithmeticTarget.B),
    0xd9: new Instruction('SET', 3, ArithmeticTarget.C),
    0xda: new Instruction('SET', 3, ArithmeticTarget.D),
    0xdb: new Instruction('SET', 3, ArithmeticTarget.E),
    0xdc: new Instruction('SET', 3, ArithmeticTarget.H),
    0xdd: new Instruction('SET', 3, ArithmeticTarget.L),
    0xde: new Instruction('SET', 3, ArithmeticTarget.HLP),
    0xdf: new Instruction('SET', 3, ArithmeticTarget.A),

    0xe0: new Instruction('SET', 4, ArithmeticTarget.B),
    0xe1: new Instruction('SET', 4, ArithmeticTarget.C),
    0xe2: new Instruction('SET', 4, ArithmeticTarget.D),
    0xe3: new Instruction('SET', 4, ArithmeticTarget.E),
    0xe4: new Instruction('SET', 4, ArithmeticTarget.H),
    0xe5: new Instruction('SET', 4, ArithmeticTarget.L),
    0xe6: new Instruction('SET', 4, ArithmeticTarget.HLP),
    0xe7: new Instruction('SET', 4, ArithmeticTarget.A),
    0xe8: new Instruction('SET', 5, ArithmeticTarget.B),
    0xe9: new Instruction('SET', 5, ArithmeticTarget.C),
    0xea: new Instruction('SET', 5, ArithmeticTarget.D),
    0xeb: new Instruction('SET', 5, ArithmeticTarget.E),
    0xec: new Instruction('SET', 5, ArithmeticTarget.H),
    0xed: new Instruction('SET', 5, ArithmeticTarget.L),
    0xee: new Instruction('SET', 5, ArithmeticTarget.HLP),
    0xef: new Instruction('SET', 5, ArithmeticTarget.A),

    0xf0: new Instruction('SET', 6, ArithmeticTarget.B),
    0xf1: new Instruction('SET', 6, ArithmeticTarget.C),
    0xf2: new Instruction('SET', 6, ArithmeticTarget.D),
    0xf3: new Instruction('SET', 6, ArithmeticTarget.E),
    0xf4: new Instruction('SET', 6, ArithmeticTarget.H),
    0xf5: new Instruction('SET', 6, ArithmeticTarget.L),
    0xf6: new Instruction('SET', 6, ArithmeticTarget.HLP),
    0xf7: new Instruction('SET', 6, ArithmeticTarget.A),
    0xf8: new Instruction('SET', 7, ArithmeticTarget.B),
    0xf9: new Instruction('SET', 7, ArithmeticTarget.C),
    0xfa: new Instruction('SET', 7, ArithmeticTarget.D),
    0xfb: new Instruction('SET', 7, ArithmeticTarget.E),
    0xfc: new Instruction('SET', 7, ArithmeticTarget.H),
    0xfd: new Instruction('SET', 7, ArithmeticTarget.L),
    0xfe: new Instruction('SET', 7, ArithmeticTarget.HLP),
    0xff: new Instruction('SET', 7, ArithmeticTarget.A),
};

export function instructionFromByte(byte: u8, isPrefixed: boolean): Instruction
{
    return isPrefixed ? prefixed[byte] : unprefixed[byte];
}
